#!/usr/bin/env python3
"""
Flatten ALL TCU modules (TFR + DXA + WGMMA + core + buffers + scheduler)
into a single Yosys-compatible SystemVerilog file for ECP5/Xilinx synthesis.

Extends flatten_tfr_v2.py's infrastructure with the full TCU module list.
"""
import re, sys, os

ROOT = sys.argv[1] if len(sys.argv) > 1 else "/home/ubuntu/grxgpu"
OUT  = sys.argv[2] if len(sys.argv) > 2 else "/tmp/tcu_flat.sv"

TCU_DIR = os.path.join(ROOT, "hw/rtl/tcu")
TFR_DIR = os.path.join(TCU_DIR, "tfr")

# ─── Module load order (dependencies → dependents) ───────────────────────
# 1. TFR submodules (already working in flatten_tfr_v2)
# 2. TFR top
# 3. TCU core modules (agu, meta, sp_mux, dsm, abuf, bbuf, tbuf, etc.)
# 4. WGMMA
# 5. UOps decoder
# 6. TCU core (selects FEDP implementation)
# 7. TCU unit (top)

TFR_MODULES = [
    # tfr/ submodules — dependency order
    "VX_tcu_tfr_wmul.sv",
    "VX_tcu_tfr_shared_mul.sv",
    "VX_tcu_tfr_mul_join.sv",
    "VX_tcu_tfr_mul_f16.sv",
    "VX_tcu_tfr_mul_f8.sv",
    "VX_tcu_tfr_mul_f4.sv",
    "VX_tcu_tfr_mul_i8.sv",
    "VX_tcu_tfr_mul_i4.sv",
    "VX_tcu_tfr_classifier.sv",
    "VX_tcu_tfr_align.sv",
    "VX_tcu_tfr_max_exp.sv",
    "VX_tcu_tfr_lane_mask.sv",
    "VX_tcu_tfr_exc_reduce.sv",
    "VX_tcu_tfr_norm_round.sv",
    "VX_tcu_tfr_acc.sv",
    "VX_tcu_fedp_tfr.sv",
]

TCU_CORE_MODULES = [
    # Core TCU modules — dependency order
    "VX_tcu_mx_scale.sv",       # MX scaling (tiny, 90 lines)
    "VX_tcu_lockstep.sv",       # Lockstep (128 lines)
    "VX_tcu_dsm.sv",            # Distributed shared memory (145 lines)
    "VX_tcu_meta.sv",           # Metadata (227 lines)
    "VX_tcu_sp_mux.sv",         # Special operand mux (186 lines)
    "VX_tcu_tbuf.sv",           # T buffer (354 lines)
    "VX_tcu_abuf.sv",           # A buffer (484 lines)
    "VX_tcu_bbuf.sv",           # B buffer (707 lines)
    "VX_tcu_agu.sv",            # Address generation unit (304 lines)
    "VX_tcu_wgmma.sv",          # WGMMA warp-group MMA (234 lines)
    "VX_tcu_uops.sv",           # Micro-op decoder (434 lines)
    "VX_tcu_core.sv",           # TCU core (711 lines) — instantiates fedp_tfr
    "VX_tcu_unit.sv",           # TCU unit top (262 lines)
]

ALL_MODULES = TFR_MODULES + TCU_CORE_MODULES

# ─── Package constants ───────────────────────────────────────────────────
# We define the critical constants inline rather than importing VX_tcu_pkg

BITS_MAP = {
    "fedp_excep_t": "3", "fedp_class_t": "4", "tcu_header_t": "32",
}

HEADER = r"""// Yosys-compatible TCU flat file (Phase A+B preprocessed)
// Auto-generated by flatten_tcu.py — full TCU for ECP5/Xilinx synthesis
`define VX_CFG_XLEN 32
`define VX_CFG_NUM_THREADS 4
`define VX_CFG_NUM_WARPS 4
`define VX_CFG_NUM_TCU_LANES 4
`define VX_CFG_ISSUE_WIDTH 4
`define VX_CFG_NUM_TCU_BLOCKS 4
`define VX_MEM_LMEM_BASE_ADDR 32'hFFFF0000
`define VX_CFG_LMEM_LOG_SIZE 14
`define VX_CFG_LMEM_NUM_BANKS 4
`define CLOG2(x) ($clog2(x))
`define LOG2UP(x) ($clog2(x))
`define UP(x) (((x) > 0) ? (x) : 1)
`define __MIN(a,b) (((a) < (b)) ? (a) : (b))
`define FORCE_BUILTIN_ADDER(x) (1)
`define MAP_AOS_SOA(i, n, a, b)
`define UNUSED_PARAM(p)
`define UNUSEDWire(w)
`define STATIC_ASSERT(cond, msg)
`define TRACING_OFF
`define TRACE_ARRAY(tag, scope, mod, idx, ...)
// Verilator lint suppression macros
`define UNUSED_VAR(x)
`define UNUSED_SPARAM(x)
`define UNUSED_PIN(x)
`define SFORMATF(x) ""
`define STRING reg
`define SCOPE_IO_DECL
`define SCOPE_IO_BIND(i)
`define SCOPE_IO_UNUSED(i)
`define SCOPE_IO_SWITCH(count)

// Type definitions from VX_tcu_pkg (packed structs)
typedef struct packed { logic is_zero; logic is_sub; logic is_inf; logic is_nan; } fedp_class_t;
typedef struct packed { logic is_inf; logic is_nan; logic sign; } fedp_excep_t;

// Format utility functions (from VX_gpu_pkg)
function automatic logic tcu_fmt_is_int(input logic [4:0] fmt);
    tcu_fmt_is_int = fmt[4];
endfunction

function automatic logic tcu_fmt_is_signed_int(input logic [3:0] int_fmt);
    tcu_fmt_is_signed_int = int_fmt[0];
endfunction

function automatic logic tcu_fmt_is_bfloat(input logic [3:0] float_fmt);
    tcu_fmt_is_bfloat = float_fmt[0];
endfunction

function automatic logic tcu_fmt_is_mx(input logic [4:0] fmt);
    case (fmt)
        5'd10, 5'd11, 5'd8, 5'd9: tcu_fmt_is_mx = 1'b1;
        default: tcu_fmt_is_mx = 1'b0;
    endcase
endfunction

function automatic int unsigned tcu_fmt_width(input logic [4:0] fmt);
    case (fmt)
        5'd2, 5'd3: tcu_fmt_width = 16;
        5'd10, 5'd11, 5'd19, 5'd20: tcu_fmt_width = 4;
        5'd4, 5'd5, 5'd17, 5'd18, 5'd8, 5'd9: tcu_fmt_width = 8;
        5'd0, 5'd16, 5'd1: tcu_fmt_width = 32;
        default: tcu_fmt_width = 0;
    endcase
endfunction

function automatic int unsigned tcu_int_fmt_width(input logic [3:0] fmt);
    case (fmt)
        4'd0: tcu_int_fmt_width = 8;
        4'd1: tcu_int_fmt_width = 16;
        4'd2: tcu_int_fmt_width = 32;
        default: tcu_int_fmt_width = 8;
    endcase
endfunction

localparam TCU_MAX_INPUTS = 16;

// ─── Behavioral blackboxes for external dependencies ─────────────────────

// VX_pipe_register — pipeline register
module VX_pipe_register #(
    parameter DATAW  = 1,
    parameter RESETW = 0,
    parameter DEPTH  = 1,
    parameter INIT_VALUE = 0
) (
    input  wire              clk,
    input  wire              reset,
    input  wire              enable,
    input  wire [DATAW-1:0]  data_in,
    output wire [DATAW-1:0]  data_out
);
    reg [DATAW-1:0] r [0:DEPTH];
    integer i;
    always_ff @(posedge clk) begin
        if (reset) begin
            for (i = 0; i <= DEPTH; i = i + 1)
                r[i] <= DATAW'(INIT_VALUE);
        end else if (enable) begin
            r[0] <= data_in;
            for (i = 1; i <= DEPTH; i = i + 1)
                r[i] <= r[i-1];
        end
    end
    assign data_out = r[DEPTH];
endmodule

// VX_tcu_tfr_wmul — mantissa multiplier (behavioral)
module VX_tcu_tfr_wmul #(
    parameter N = 4, M = 4, LANES = 1, SHARED_B = 0, P = 8, USE_DSP = 0
) (
    input  wire [LANES*N-1:0] a,
    input  wire [LANES*M-1:0] b,
    output wire [LANES*P-1:0] p
);
    genvar i;
    generate
        for (i = 0; i < LANES; i = i + 1) begin : g_mul
            localparam BI = (SHARED_B != 0) ? 0 : i;
            assign p[i*P +: P] = a[i*N +: N] * b[BI*M +: M];
        end
    endgenerate
endmodule

// VX_ks_adder — carry-select adder (behavioral)
module VX_ks_adder #(
    parameter N = 16, parameter BYPASS = 0
) (
    input  wire [N-1:0] dataa,
    input  wire [N-1:0] datab,
    input  wire         cin,
    output wire [N-1:0] sum,
    output wire         cout
);
    assign {cout, sum} = dataa + datab + N'(cin);
endmodule

// VX_csa_tree — carry-save adder tree (behavioral)
module VX_csa_tree #(
    parameter N = 16, parameter W = 8, parameter K = 6,
    parameter BAL = 1, parameter S = 12
) (
    input  wire [N*W-1:0] operands,
    output wire [S-1:0]   sum,
    output wire [S-1:0]   carry
);
    integer i;
    reg [S-1:0] total;
    always_comb begin
        total = 0;
        for (i = 0; i < N; i = i + 1)
            total = total + S'(operands[i*W +: W]);
    end
    assign sum = total;
    assign carry = 0;
endmodule

// VX_lzc — leading zero count (behavioral)
module VX_lzc #(
    parameter N = 2, parameter REVERSE = 0, parameter LOGN = 1
) (
    input  wire [N-1:0]    data_in,
    output wire [LOGN-1:0] data_out,
    output wire            valid_out
);
    integer i;
    reg [LOGN-1:0] count;
    reg found;
    always_comb begin
        found = 0;
        count = 0;
        for (i = 0; i < N; i = i + 1) begin
            if (!found && data_in[REVERSE ? (N-1-i) : i]) begin
                count = LOGN'(i);
                found = 1;
            end
        end
    end
    assign data_out = count;
    assign valid_out = |data_in;
endmodule

// VX_popcount — population count (behavioral)
module VX_popcount #(
    parameter N = 64, parameter M = 7
) (
    input  wire [N-1:0] data_in,
    output wire [M-1:0] data_out
);
    integer i;
    reg [M-1:0] count;
    always_comb begin
        count = 0;
        for (i = 0; i < N; i = i + 1)
            count = count + M'(data_in[i]);
    end
    assign data_out = count;
endmodule

// VX_generic_arbiter — generic arbiter (behavioral: priority)
module VX_generic_arbiter #(
    parameter NUM_REQS = 4,
    parameter WORD_WIDTH = 1,
    parameter LOG_NUM_REQS = 2
) (
    input  wire [NUM_REQS-1:0]          requests,
    input  wire                          any_in,
    output wire [LOG_NUM_REQS-1:0]      grant_index,
    output wire [NUM_REQS-1:0]          grant_onehot,
    output wire                          grant_valid
);
    integer i;
    reg [LOG_NUM_REQS-1:0] idx;
    reg found;
    always_comb begin
        found = 0;
        idx = 0;
        for (i = 0; i < NUM_REQS; i = i + 1) begin
            if (!found && requests[i]) begin
                idx = LOG_NUM_REQS'(i);
                found = 1;
            end
        end
    end
    assign grant_index = idx;
    assign grant_onehot = found ? (NUM_REQS'(1) << idx) : '0;
    assign grant_valid = found;
endmodule

// VX_fifo_queue — FIFO queue (behavioral: shift register)
module VX_fifo_queue #(
    parameter DATAW = 1,
    parameter DEPTH = 1,
    parameter ALM_FULL = 0,
    parameter ALM_EMPTY = 0
) (
    input  wire              clk,
    input  wire              reset,
    input  wire              push,
    input  wire              pop,
    input  wire [DATAW-1:0]  data_in,
    output wire [DATAW-1:0]  data_out,
    output wire              full,
    output wire              empty
);
    reg [DATAW-1:0] mem [0:DEPTH-1];
    reg [$clog2(DEPTH):0] rptr, wptr, count;
    integer i;

    always_ff @(posedge clk) begin
        if (reset) begin
            rptr <= 0; wptr <= 0; count <= 0;
        end else begin
            if (push && !full) begin
                mem[wptr] <= data_in;
                wptr <= (wptr == DEPTH-1) ? 0 : wptr + 1;
                count <= count + 1;
            end
            if (pop && !empty) begin
                rptr <= (rptr == DEPTH-1) ? 0 : rptr + 1;
                count <= count - 1;
            end
        end
    end
    assign data_out = mem[rptr];
    assign full = (count == DEPTH);
    assign empty = (count == 0);
endmodule

// VX_tcu_tfr_pipe_register — TFR-specific pipeline register (alias)
module VX_tcu_tfr_pipe_register #(
    parameter DATAW  = 1,
    parameter RESETW = 0,
    parameter DEPTH  = 1,
    parameter INIT_VALUE = 0
) (
    input  wire              clk,
    input  wire              reset,
    input  wire              enable,
    input  wire [DATAW-1:0]  data_in,
    output wire [DATAW-1:0]  data_out
);
    VX_pipe_register #(.DATAW(DATAW), .RESETW(RESETW), .DEPTH(DEPTH), .INIT_VALUE(INIT_VALUE))
    u_pipe (.clk(clk), .reset(reset), .enable(enable), .data_in(data_in), .data_out(data_out));
endmodule

"""

# ─── Phase A transforms ──────────────────────────────────────────────────

def strip_preprocessor_blocks(content):
    """Strip preprocessor directives but KEEP their bodies.
    ifdef=keep, ifndef=skip, elsif/else=flip, define/undef/include=remove.
    """
    lines = content.split("\n")
    result = []
    stack = []  # 'keep' or 'skip'

    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Track preprocessor state but REMOVE all directive lines from output
        if stripped.startswith("`ifdef "):
            stack.append('keep')
            i += 1
            continue
        elif stripped.startswith("`ifndef "):
            stack.append('skip')
            i += 1
            continue
        elif stripped.startswith("`elsif ") or stripped.startswith("`else"):
            if stack:
                stack[-1] = 'skip' if stack[-1] == 'keep' else 'keep'
            i += 1
            continue
        elif stripped.startswith("`endif"):
            if stack:
                stack.pop()
            i += 1
            continue
        elif stripped.startswith("`define ") or stripped.startswith("`undef ") or stripped.startswith("`include "):
            i += 1
            continue
        elif stack and stack[-1] == 'skip':
            i += 1
            continue

        result.append(line)
        i += 1

    return "\n".join(result)


def strip_simulation_macros(content):
    """Strip $display, $write, $monitor, TRACE, DBG_TRACE_TCU (multi-line aware)."""
    # Strip $display/$write/$monitor with parenthesis-depth counting
    for pat in ["$display", "$write", "$monitor"]:
        result = []
        i = 0
        while i < len(content):
            idx = content.find(pat, i)
            if idx < 0:
                result.append(content[i:])
                break
            result.append(content[i:idx])
            paren_start = content.find('(', idx + len(pat))
            if paren_start < 0:
                i = idx + len(pat)
                continue
            depth = 1
            j = paren_start + 1
            while j < len(content) and depth > 0:
                if content[j] == '(':
                    depth += 1
                elif content[j] == ')':
                    depth -= 1
                j += 1
            # Also skip trailing semicolon
            while j < len(content) and content[j] in (' ', '\t'):
                j += 1
            if j < len(content) and content[j] == ';':
                j += 1
            i = j
        content = "".join(result)

    # Strip TRACE / TRACE_ARRAY
    for pat in ["`TRACE", "`TRACE_ARRAY"]:
        result = []
        i = 0
        while i < len(content):
            idx = content.find(pat, i)
            if idx < 0:
                result.append(content[i:])
                break
            result.append(content[i:idx])
            paren_start = content.find('(', idx + len(pat))
            if paren_start < 0:
                i = idx + len(pat)
                continue
            depth = 1
            j = paren_start + 1
            while j < len(content) and depth > 0:
                if content[j] == '(':
                    depth += 1
                elif content[j] == ')':
                    depth -= 1
                j += 1
            while j < len(content) and content[j] in (' ', '\t', ';'):
                j += 1
            i = j
        content = "".join(result)

    # Strip DBG_TRACE_TCU blocks
    content = re.sub(r'`ifdef\s+DBG_TRACE_TCU.*?`endif[^\n]*\n', '', content, flags=re.DOTALL)

    return content


def strip_simulation_only(content):
    """Strip `ifndef SYNTHESIS ... `endif blocks."""
    lines = content.split('\n')
    result = []
    skip = False
    depth = 0
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("`ifndef SYNTHESIS"):
            skip = True
            depth = 1
            continue
        if skip:
            if stripped.startswith("`ifdef") or stripped.startswith("`ifndef"):
                depth += 1
            elif stripped.startswith("`endif"):
                depth -= 1
                if depth == 0:
                    skip = False
            continue
        result.append(line)
    return '\n'.join(result)


def transform(content):
    """Apply all Phase A transforms."""
    content = strip_preprocessor_blocks(content)
    content = strip_simulation_only(content)
    content = strip_simulation_macros(content)

    # FORCE_BUILTIN_ADDER
    content = re.sub(r'`FORCE_BUILTIN_ADDER\s*\(([^)]+)\)', r'1', content)
    content = re.sub(r'^\s*`FORCE_BUILTIN_ADDER[^\n]*\n?', '', content, flags=re.MULTILINE)

    # Backtick-escaped constants → literals
    for pkg_const in re.findall(r'`(\w+)', content):
        if pkg_const in ('ifdef', 'ifndef', 'endif', 'elsif', 'else', 'define', 'undef', 'include',
                         'TRACE', 'TRACE_ARRAY', 'UNUSED_PARAM', 'UNUSEDWire', 'STATIC_ASSERT',
                         'TRACING_OFF', 'FORCE_BUILTIN_ADDER', 'CLOG2', 'LOG2UP', 'UP', '__MIN',
                         'VX_CFG_XLEN', 'VX_CFG_NUM_THREADS', 'VX_CFG_NUM_WARPS', 'VX_CFG_NUM_TCU_LANES',
                         'VX_CFG_ISSUE_WIDTH', 'VX_CFG_NUM_TCU_BLOCKS',
                         'VX_MEM_LMEM_BASE_ADDR', 'VX_CFG_LMEM_LOG_SIZE', 'VX_CFG_LMEM_NUM_BANKS',
                         'MAP_AOS_SOA',
                         'UNUSED_VAR', 'UNUSED_SPARAM', 'UNUSED_PIN', 'SFORMATF', 'STRING',
                         'SCOPE_IO_DECL', 'SCOPE_IO_BIND', 'SCOPE_IO_UNUSED', 'SCOPE_IO_SWITCH'):
            continue
        if pkg_const in BITS_MAP:
            content = content.replace(f'`{pkg_const}', BITS_MAP[pkg_const])

    # Convert import statements to comments (including inline module imports)
    content = re.sub(r'^\s*import\s+\w+::\*;\s*$', '// [stripped import]', content, flags=re.MULTILINE)
    # Strip inline imports from module declarations: 'module X import Pkg1::*, Pkg2::*; #(' -> 'module X #('
    content = re.sub(r'^(module\s+\w+)\s+import\s+[\w:*,\s]+;\s*', r'\1 ', content, flags=re.MULTILINE)
    # Strip 'parameter reg' → 'parameter' (SystemVerilog type parameter syntax)
    content = re.sub(r'\bparameter\s+reg\b', 'parameter', content)

    # $clog2 → $clog2 (keep — Yosys supports it)
    # $bits() → computed constants
    content = re.sub(r'\$bits\(([^)]+)\)', r'32', content)

    # UNUSED_PARAM / UNUSEDWire / UNUSED_VAR / UNUSED_SPARAM / UNUSED_PIN → empty
    for macro_name in ['UNUSED_PARAM', 'UNUSEDWire', 'STATIC_ASSERT',
                       'UNUSED_VAR', 'UNUSED_SPARAM', 'UNUSED_PIN']:
        content = re.sub(rf'`{macro_name}\s*\([^)]*\)', '', content)
    # SFORMATF → empty string
    content = re.sub(r'`SFORMATF\s*\([^)]*\)', '""', content)
    # SCOPE_IO_* → empty
    for macro_name in ['SCOPE_IO_DECL', 'SCOPE_IO_BIND', 'SCOPE_IO_UNUSED', 'SCOPE_IO_SWITCH']:
        content = re.sub(rf'`{macro_name}\s*\([^)]*\)', '', content)
        content = re.sub(rf'`{macro_name}', '', content)
    # STRING → reg (used as parameter type)
    content = re.sub(r'`STRING\s+', 'reg ', content)
    content = re.sub(r'`STRING', 'reg', content)
    # RUNTIME_ASSERT / ASSIGN_VX_MEM_BUS_IF → empty (debug/synthesis macros)
    content = re.sub(r'`RUNTIME_ASSERT\s*\([^)]*\)', '', content)
    content = re.sub(r'`ASSIGN_VX_MEM_BUS_IF\s*\([^)]*\)', '', content)
    # MAX(a,b) → ((a) > (b) ? (a) : (b))
    content = re.sub(r'`MAX\s*\(([^,]+),\s*([^)]+)\)', r'((\1) > (\2) ? (\1) : (\2))', content)

    # `include "..." → remove
    content = re.sub(r'^\s*`include\s+"[^"]*"\s*$', '', content, flags=re.MULTILINE)

    return content


# ─── Phase B: Gen-scoped variable hoisting ───────────────────────────────

def hoist_gen_scoped(mod_text, max_loop=16):
    """Hoist wire/logic/reg declarations from inside for(genvar) blocks to module scope."""
    lines = mod_text.split('\n')
    to_hoist = []

    gen_stack = []
    begin_depth = 0

    for i, line in enumerate(lines):
        s = line.strip()
        if re.search(r'\bbegin\b', s):
            begin_depth += 1

        gm = re.match(r'for\s*\(\s*genvar\s+(\w+)\s*=', s)
        if gm:
            var = gm.group(1)
            lm = re.search(r'begin\s*:\s*(\w+)', s)
            label = lm.group(1) if lm else f'gen{i}'
            gen_stack.append((var, label, begin_depth - 1))

        if re.match(r'^\s*end\b', s) and not re.match(r'^\s*end(module|case|function|task)', s):
            if gen_stack and begin_depth - 1 == gen_stack[-1][2]:
                gen_stack.pop()
            begin_depth = max(0, begin_depth - 1)
            continue

        if gen_stack:
            var, label, _ = gen_stack[-1]
            dm = re.match(r'^[ \t]*(wire|logic|reg)\s+(.*);\s*$', s)
            if dm:
                dtype = dm.group(1)
                rest = dm.group(2).strip()
                width_prefix = ''
                names_part = rest
                wm = re.match(r'((?:\[[^\]]+\]\s*)+)', rest)
                if wm:
                    width_prefix = wm.group(1).strip()
                    names_part = rest[wm.end():].strip()
                elif rest.startswith('signed'):
                    wm2 = re.match(r'signed\s+((?:\[[^\]]+\]\s*)+)', rest)
                    if wm2:
                        width_prefix = 'signed ' + wm2.group(1).strip()
                        names_part = rest[wm2.end():].strip()

                if '=' in names_part:
                    name_candidates = [names_part.strip()]
                else:
                    name_candidates = [n.strip() for n in names_part.split(',')]

                for name_raw in name_candidates:
                    name_raw = name_raw.strip()
                    name_raw = re.sub(r'\s*\[.*$', '', name_raw)
                    name_raw = re.sub(r'\s*=.*$', '', name_raw)
                    name = name_raw.split()[0] if name_raw.split() else ''
                    if not name or not re.match(r'[a-zA-Z_]', name):
                        continue
                    width = width_prefix
                    if width and re.search(rf'\b{re.escape(var)}\b', width):
                        continue
                    if width and re.search(r'[a-zA-Z_]\w*\s*[-+*/]', width):
                        for lp in re.finditer(r'localparam\s+(?:\[.*?\]\s+)?(\w+)\s*=\s*([^;]+);', mod_text):
                            lp_name, lp_val = lp.group(1), lp.group(2).strip()
                            if lp_val.isdigit():
                                width = re.sub(rf'\b{re.escape(lp_name)}\b', lp_val, width)
                        for wm_eval in re.finditer(r'\[(\d+)\s*([-+])\s*(\d+)\s*:\s*(\d+)\]', width):
                            a, op, b, lo = int(wm_eval.group(1)), wm_eval.group(2), int(wm_eval.group(3)), wm_eval.group(4)
                            result = a - b if op == '-' else a + b
                            width = width[:wm_eval.start()] + f'[{result}:{lo}]' + width[wm_eval.end():]
                        if re.search(r'[a-zA-Z_]', re.sub(r'\[|\]|:', '', width)):
                            continue
                    if name and not name.startswith(var):
                        to_hoist.append((i, name, dtype, width, var, label))

    if not to_hoist:
        return mod_text

    def find_gen_scope(line_idx):
        depth = 0
        for j in range(line_idx, -1, -1):
            s = lines[j].strip()
            if re.match(r'^\s*end\b', s) and not re.match(r'^\s*end(module|case|function|task)', s):
                depth += 1
            if re.search(r'\bbegin\b', s):
                depth -= 1
            if depth < 0 and re.match(r'for\s*\(\s*genvar', s):
                start = j
                depth2 = 0
                for k in range(j, len(lines)):
                    sk = lines[k].strip()
                    if re.search(r'\bbegin\b', sk):
                        depth2 += 1
                    if re.match(r'^\s*end\b', sk) and not re.match(r'^\s*end(module|case|function|task)', sk):
                        depth2 -= 1
                        if depth2 < 0:
                            return (start, k)
                return (start, len(lines) - 1)
        return (0, len(lines) - 1)

    decl_scopes = []
    for line_idx, name, dtype, width, var, label in to_hoist:
        start, end = find_gen_scope(line_idx)
        decl_scopes.append((line_idx, name, dtype, width, var, label, start, end))

    from collections import defaultdict
    lines_by_idx = defaultdict(list)
    for entry in decl_scopes:
        lines_by_idx[entry[0]].append(entry)

    for line_idx in sorted(lines_by_idx.keys(), reverse=True):
        entries = lines_by_idx[line_idx]
        scope_start = entries[0][6]
        scope_end = entries[0][7]
        for _, name, dtype, width, var, label, _, _ in entries:
            hname = f'{label}_{name}'
            for j in range(scope_start, scope_end + 1):
                if j == line_idx:
                    continue
                lines[j] = re.sub(rf'(?<!_)\b{re.escape(name)}\b', f'{hname}[{var}]', lines[j])
        lines[line_idx] = ''

    hoisted = []
    seen = set()
    for _, name, dtype, width, var, label in to_hoist:
        hname = f'{label}_{name}'
        if hname in seen:
            continue
        seen.add(hname)
        if width:
            hoisted.append(f'    wire {width} {hname} [0:{max_loop-1}];')
        else:
            hoisted.append(f'    wire [7:0] {hname} [0:{max_loop-1}];')

    result_lines = []
    inserted = False
    for i, line in enumerate(lines):
        result_lines.append(line)
        if not inserted and line.strip() == ');':
            result_lines.append('')
            result_lines.append('    // Phase B: Hoisted generate-scoped wires')
            result_lines.extend(hoisted)
            result_lines.append('')
            inserted = True

    return '\n'.join(result_lines)


# ─── Main ─────────────────────────────────────────────────────────────────

def main():
    # Read and transform each module
    all_modules = []
    seen_modules = set()

    for mod_file in ALL_MODULES:
        # Determine directory
        if mod_file in TFR_MODULES:
            fpath = os.path.join(TFR_DIR, mod_file)
        else:
            fpath = os.path.join(TCU_DIR, mod_file)

        if not os.path.exists(fpath):
            print(f"  WARNING: {mod_file} not found, skipping")
            continue

        with open(fpath) as f:
            content = f.read()

        # Strip copyright header
        lines = content.split('\n')
        mod_start = 0
        for idx, line in enumerate(lines):
            if re.match(r'\s*module\s+', line):
                mod_start = idx
                break

        # Find module name
        m = re.match(r'\s*module\s+(\w+)', lines[mod_start])
        if not m:
            continue
        mod_name = m.group(1)
        if mod_name in seen_modules:
            continue
        seen_modules.add(mod_name)

        # Apply Phase A transforms
        mod_body = '\n'.join(lines[mod_start:])
        mod_body = transform(mod_body)

        # Apply Phase B hoisting
        mod_body = hoist_gen_scoped(mod_body)

        all_modules.append(mod_body)

    # Compose output
    with open(OUT, 'w') as f:
        f.write(HEADER)
        f.write('\n\n')
        for i, mod in enumerate(all_modules):
            f.write(mod)
            f.write('\n\n')

    total_lines = sum(m.count('\n') for m in all_modules) + HEADER.count('\n')
    print(f"Flattened {len(all_modules)} TCU modules -> {OUT}")
    print(f"  File size: {os.path.getsize(OUT)} bytes")
    print(f"  Total lines: {total_lines}")


if __name__ == '__main__':
    main()
