#!/usr/bin/env python3
"""
Flatten ALL TCU modules (TFR + DXA + WGMMA + core + buffers + scheduler)
into a single Yosys-compatible SystemVerilog file for ECP5/Xilinx synthesis.

Extends flatten_tfr_v2.py's infrastructure with the full TCU module list.
"""
import re, sys, os

ROOT = sys.argv[1] if len(sys.argv) > 1 else "/home/ubuntu/grxgpu"
OUT  = sys.argv[2] if len(sys.argv) > 2 else "/tmp/tcu_flat.sv"

TCU_DIR = os.path.join(ROOT, "hw/rtl/tcu")
TFR_DIR = os.path.join(TCU_DIR, "tfr")

# ─── Module load order (dependencies → dependents) ───────────────────────
# 1. TFR submodules (already working in flatten_tfr_v2)
# 2. TFR top
# 3. TCU core modules (agu, meta, sp_mux, dsm, abuf, bbuf, tbuf, etc.)
# 4. WGMMA
# 5. UOps decoder
# 6. TCU core (selects FEDP implementation)
# 7. TCU unit (top)

TFR_MODULES = [
    # tfr/ submodules — dependency order
    "VX_tcu_tfr_wmul.sv",
    "VX_tcu_tfr_shared_mul.sv",
    "VX_tcu_tfr_mul_join.sv",
    "VX_tcu_tfr_mul_f16.sv",
    "VX_tcu_tfr_mul_f8.sv",
    "VX_tcu_tfr_mul_f4.sv",
    "VX_tcu_tfr_mul_i8.sv",
    "VX_tcu_tfr_mul_i4.sv",
    "VX_tcu_tfr_classifier.sv",
    "VX_tcu_tfr_align.sv",
    "VX_tcu_tfr_max_exp.sv",
    "VX_tcu_tfr_lane_mask.sv",
    "VX_tcu_tfr_exc_reduce.sv",
    "VX_tcu_tfr_norm_round.sv",
    "VX_tcu_tfr_acc.sv",
    "VX_tcu_fedp_tfr.sv",
]

TCU_CORE_MODULES = [
    # Core TCU modules — dependency order
    # Modules WITHOUT SV interfaces (can synthesize directly)
    "VX_tcu_mx_scale.sv",       # MX scaling (tiny, 90 lines)
    "VX_tcu_lockstep.sv",       # Lockstep (128 lines)
    "VX_tcu_dsm.sv",            # Distributed shared memory (145 lines)
    "VX_tcu_meta.sv",           # Metadata (227 lines)
    "VX_tcu_sp_mux.sv",         # Special operand mux (186 lines)
    "VX_tcu_uops.sv",           # Micro-op decoder (434 lines)
    # Modules WITH SV interfaces (expanded post-flatten by expand_interfaces.py)
    "VX_tcu_tbuf.sv",           # T buffer — has VX_mem_bus_if
    "VX_tcu_abuf.sv",           # A buffer — has VX_mem_bus_if
    "VX_tcu_bbuf.sv",           # B buffer — has VX_mem_bus_if
    "VX_tcu_agu.sv",            # AGU — has VX_mem_bus_if
    "VX_tcu_wgmma.sv",          # WGMMA — has VX_mem_bus_if
    "VX_tcu_core.sv",           # TCU core — has VX_execute_if, VX_result_if
    "VX_tcu_unit.sv",           # TCU unit — has VX_mem_bus_if, VX_dispatch_if, etc.
]

ALL_MODULES = TFR_MODULES + TCU_CORE_MODULES

# ─── Package constants ───────────────────────────────────────────────────
# We define the critical constants inline rather than importing VX_tcu_pkg

BITS_MAP = {
    "fedp_excep_t": "3", "fedp_class_t": "4", "tcu_header_t": "32",
}

HEADER = r"""// Yosys-compatible TCU flat file (Phase A+B preprocessed)
// Auto-generated by flatten_tcu.py — full TCU for ECP5/Xilinx synthesis
`define VX_CFG_XLEN 32
`define VX_CFG_NUM_THREADS 4
`define VX_CFG_NUM_WARPS 4
`define VX_CFG_NUM_TCU_LANES 4
`define VX_CFG_ISSUE_WIDTH 4
`define VX_CFG_NUM_TCU_BLOCKS 4
`define VX_MEM_LMEM_BASE_ADDR 32'hFFFF0000
`define VX_CFG_LMEM_LOG_SIZE 14
`define VX_CFG_LMEM_NUM_BANKS 4
`define VX_CFG_SIMD_WIDTH `VX_CFG_NUM_THREADS
`define VX_CFG_TCU_WGMMA_ENABLE 1
`define VX_CFG_TCU_FEDP2K 1
`define VX_CFG_TCU_FP16_ENABLE 1
`define VX_CFG_TCU_INT8_ENABLE 1
`define VX_CFG_TCU_INT4_ENABLE 1
`define VX_CFG_TCU_FP8_ENABLE 1
`define VX_CFG_TCU_FP4_ENABLE 1
`define VX_CFG_TCU_TF32_ENABLE 1
`define VX_CFG_TCU_MX_ENABLE 1
`define VX_CFG_TCU_MXFP4_ENABLE 1
`define VX_CFG_TCU_NVFP4_ENABLE 1
`define VX_CFG_TCU_SPARSE_ENABLE 1
`define VX_CFG_TCU_DSM_ENABLE 1
`define VX_CFG_TCU_WGMMA_ENABLED 1
`define VX_CFG_TCU_SPARSE_ENABLED 0
`define VX_CFG_TCU_FP16_ENABLED 1
`define VX_CFG_TCU_TYPE_TFR 1

`define VX_CFG_TCU_TYPE_TFR 1

`define CLOG2(x) ($clog2(x))
`define LOG2UP(x) ($clog2(x))
`define UP(x) (((x) > 0) ? (x) : 1)
`define __MIN(a,b) (((a) < (b)) ? (a) : (b))
`define FORCE_BUILTIN_ADDER(x) (1)
`define MAP_AOS_SOA(i, n, a, b)
`define UNUSED_PARAM(p)
`define UNUSEDWire(w)
`define STATIC_ASSERT(cond, msg)
`define TRACING_OFF
`define TRACE_ARRAY(tag, scope, mod, idx)
// Verilator lint suppression macros
`define UNUSED_VAR(x)
`define UNUSED_SPARAM(x)
`define UNUSED_PIN(x)
`define SFORMATF(x) ""
`define STRING reg
`define SCOPE_IO_DECL
`define SCOPE_IO_BIND(i)
`define SCOPE_IO_UNUSED(i)
`define SCOPE_IO_SWITCH(count)

        // GPU package parameters (from VX_gpu_pkg.sv)
    localparam UUID_WIDTH = 44;
    localparam NW_WIDTH = `CLOG2(`VX_CFG_NUM_WARPS);
    localparam NCTA_WIDTH = 14;
    localparam SIMD_IDX_W = 1;
    localparam PC_BITS = `VX_CFG_XLEN;
    localparam NUM_XREGS = 2;
    localparam NUM_REGS_BITS = 5;
    localparam BYTESEL_BITS = 4;
    localparam INST_OP_BITS = 4;
    localparam NUM_SRC_OPDS = 3;
    localparam EX_BITS = 2;
    localparam ISSUE_WIS_W = 1;
    localparam ISSUE_WIDTH = `VX_CFG_ISSUE_WIDTH;
    localparam MEM_ATTR_WIDTH = 3;
    localparam NUM_REGS = 32;
    localparam XLENB = 4;
    localparam XLENB_W = 2;
    localparam NCTA_BITS = 14;
    localparam NUM_EX_UNITS = 4;
    localparam NUM_THREADS = `VX_CFG_NUM_THREADS;

    // op_args_t — packed union, declared as wide logic
    typedef logic [127:0] op_args_t;

typedef struct packed {
        logic [UUID_WIDTH-1:0]              uuid;
        logic [ISSUE_WIS_W-1:0]             wis;
        logic [NCTA_WIDTH-1:0]              cta_id;
        logic [SIMD_IDX_W-1:0]              sid;
        logic [`VX_CFG_SIMD_WIDTH-1:0]             tmask;
        logic [PC_BITS-1:0]                 PC;
        logic                               wb;
        logic [NUM_XREGS-1:0]               wr_xregs;
        logic [NUM_REGS_BITS-1:0]           rd;
        logic [BYTESEL_BITS-1:0]            bytesel;
        logic [INST_OP_BITS-1:0]            op_type;
        op_args_t                           op_args;
        logic [`VX_CFG_SIMD_WIDTH-1:0][`VX_CFG_XLEN-1:0]  rs1_data;
        logic [`VX_CFG_SIMD_WIDTH-1:0][`VX_CFG_XLEN-1:0]  rs2_data;
        logic [`VX_CFG_SIMD_WIDTH-1:0][`VX_CFG_XLEN-1:0]  rs3_data;
        logic                               sop;
        logic                               eop;
    } dispatch_t;
typedef struct packed {
        logic [UUID_WIDTH-1:0]              uuid;
        logic [NW_WIDTH-1:0]                wid;
        logic [NCTA_WIDTH-1:0]              cta_id;
        logic [SIMD_IDX_W-1:0]              sid;
        logic [`VX_CFG_SIMD_WIDTH-1:0]             tmask;
        logic [PC_BITS-1:0]                 PC;
        logic                               wb;
        logic [NUM_XREGS-1:0]               wr_xregs;
        logic [NUM_REGS_BITS-1:0]           rd;
        logic [BYTESEL_BITS-1:0]            bytesel;
        logic [`VX_CFG_SIMD_WIDTH-1:0][`VX_CFG_XLEN-1:0]  data;
        logic                               sop;
        logic                               eop;
    } commit_t;

// Type definitions from VX_tcu_pkg (packed structs)
localparam TCU_FP32_ID = 0;
localparam TCU_TF32_ID = 1;
localparam TCU_FP16_ID = 2;
localparam TCU_BF16_ID = 3;
localparam TCU_FP8_ID = 4;
localparam TCU_BF8_ID = 5;
localparam TCU_MXFP8_ID = 8;
localparam TCU_MXBF8_ID = 9;
localparam TCU_MXFP4_ID = 10;
localparam TCU_NVFP4_ID = 11;
localparam TCU_I32_ID = 16;
localparam TCU_I8_ID = 17;
localparam TCU_U8_ID = 18;
localparam TCU_I4_ID = 19;
localparam TCU_U4_ID = 20;
localparam TCU_FMT_WIDTH = 5;
localparam TCU_NT = `VX_CFG_NUM_THREADS;
localparam TCU_WG_NRA = 4;
localparam TCU_WG_NR = 32;
localparam TCU_NR = 8;
localparam TCU_DK = 0;
localparam TCU_DP = 0;
localparam TCU_TILE_CAP = TCU_NT * TCU_NR;
localparam TCU_LG_TILE_CAP = $clog2(TCU_TILE_CAP);
localparam TCU_TILE_EN = TCU_LG_TILE_CAP / 2;
localparam TCU_TILE_EM = TCU_LG_TILE_CAP - TCU_TILE_EN;
localparam TCU_TILE_M = 1 << TCU_TILE_EM;
localparam TCU_TILE_N = 1 << TCU_TILE_EN;
localparam TCU_TILE_K = (TCU_DK != 0) ? TCU_DK : (TCU_DP != 0) ? TCU_DP : (TCU_TILE_CAP / ((TCU_TILE_M > TCU_TILE_N) ? TCU_TILE_M : TCU_TILE_N));
localparam TCU_BLOCK_CAP = TCU_NT;
localparam TCU_LG_BLOCK_CAP = $clog2(TCU_BLOCK_CAP);
localparam TCU_BLOCK_EN = TCU_LG_BLOCK_CAP / 2;
localparam TCU_BLOCK_EM = TCU_LG_BLOCK_CAP - TCU_BLOCK_EN;
localparam TCU_TC_M = 1 << TCU_BLOCK_EM;
localparam TCU_TC_N = 1 << TCU_BLOCK_EN;
localparam TCU_TC_K = (TCU_DP != 0) ? TCU_DP : (TCU_BLOCK_CAP / ((TCU_TC_M > TCU_TC_N) ? TCU_TC_M : TCU_TC_N));
localparam TCU_M_STEPS = TCU_TILE_M / TCU_TC_M;
localparam TCU_N_STEPS = TCU_TILE_N / TCU_TC_N;
localparam TCU_K_STEPS = TCU_TILE_K / TCU_TC_K;
localparam TCU_A_BLOCK_SIZE = TCU_TC_M * TCU_TC_K;
localparam TCU_A_SUB_BLOCKS = TCU_BLOCK_CAP / TCU_A_BLOCK_SIZE;
localparam TCU_B_BLOCK_SIZE = TCU_TC_K * TCU_TC_N;
localparam TCU_B_SUB_BLOCKS = TCU_BLOCK_CAP / TCU_B_BLOCK_SIZE;
localparam TCU_WG_TILE_M = 2 * TCU_TC_M;
localparam TCU_WG_TILE_K = 2 * TCU_TC_K;
localparam TCU_WG_FEDP_K = 2 * TCU_TC_K;
localparam TCU_WG_FEDP_K = TCU_TC_K;
localparam TCU_WG_TILE_N = (TCU_WG_NR * TCU_NT) / TCU_WG_TILE_M;
localparam TCU_WG_M_STEPS = TCU_WG_TILE_M / TCU_TC_M;
localparam TCU_WG_N_STEPS = TCU_WG_TILE_N / TCU_TC_N;
localparam TCU_WG_K_STEPS = TCU_WG_TILE_K / TCU_WG_FEDP_K;
localparam TCU_WG_UOPS = TCU_WG_M_STEPS * TCU_WG_N_STEPS * TCU_WG_K_STEPS;
localparam TCU_WG_A_BLOCK_SIZE = TCU_TC_M * TCU_TC_K;
localparam TCU_WG_A_DATA_SIZE = TCU_TC_M * TCU_WG_FEDP_K;
localparam TCU_WG_A_SUB_BLOCKS = TCU_BLOCK_CAP / TCU_WG_A_BLOCK_SIZE;
localparam TCU_WG_B_BLOCK_SIZE = TCU_WG_FEDP_K * TCU_TC_N;
localparam TCU_WG_B_SUB_BLOCKS = TCU_BLOCK_CAP / TCU_WG_B_BLOCK_SIZE;
localparam SYM_SPARSE = `VX_CFG_TCU_WGMMA_ENABLED ? 0 : (TCU_BLOCK_EM == TCU_BLOCK_EN);
localparam TCU_B_BLOCK_SIZE_SP = SYM_SPARSE ? TCU_BLOCK_CAP : (TCU_TC_K * TCU_TC_N) * 2;
localparam TCU_B_SUB_BLOCKS_SP = TCU_BLOCK_CAP / TCU_B_BLOCK_SIZE_SP;
localparam TCU_WG_B_BLOCK_SIZE_SP = TCU_TC_K * TCU_TC_N * 2;
localparam TCU_WG_RS2_WIDTH_DENSE = (TCU_WG_B_BLOCK_SIZE > TCU_BLOCK_CAP) ? TCU_WG_B_BLOCK_SIZE : TCU_BLOCK_CAP;
localparam TCU_WG_RS2_WIDTH = `VX_CFG_TCU_SPARSE_ENABLED
        ? ((TCU_WG_B_BLOCK_SIZE_SP > TCU_WG_RS2_WIDTH_DENSE) ? TCU_WG_B_BLOCK_SIZE_SP : TCU_WG_RS2_WIDTH_DENSE)
        : TCU_WG_RS2_WIDTH_DENSE;
localparam TCU_MIN_FMT_WIDTH = 4;
localparam TCU_MAX_ELT_RATIO = 32 / TCU_MIN_FMT_WIDTH;
localparam TCU_MAX_META_ROW_WIDTH = TCU_TC_K * 2 * TCU_MAX_ELT_RATIO;
localparam TCU_MAX_META_BLOCK_WIDTH = TCU_NT   * 2 * TCU_MAX_ELT_RATIO;
localparam TCU_META_PER_WARP_DEPTH = TCU_M_STEPS * (TCU_K_STEPS / 2);
localparam TCU_META_COLS_PER_LOAD = (TCU_BLOCK_CAP >= TCU_META_PER_WARP_DEPTH)
        ? (TCU_BLOCK_CAP / TCU_META_PER_WARP_DEPTH) : 1;
localparam TCU_BANKS_PER_STORE = (TCU_NT < TCU_META_PER_WARP_DEPTH)
        ? TCU_NT : TCU_META_PER_WARP_DEPTH;
localparam TCU_STORES_PER_COL = (TCU_META_PER_WARP_DEPTH + TCU_NT - 1) / TCU_NT;
localparam TCU_WG_META_PER_WARP_DEPTH = TCU_WG_M_STEPS * (TCU_WG_K_STEPS / 2);
localparam TCU_WG_META_COLS_PER_LOAD = (TCU_BLOCK_CAP >= TCU_WG_META_PER_WARP_DEPTH)
        ? (TCU_BLOCK_CAP / TCU_WG_META_PER_WARP_DEPTH) : 1;
localparam TCU_WG_STORES_PER_COL = (TCU_WG_META_PER_WARP_DEPTH + TCU_NT - 1) / TCU_NT;
localparam TCU_NRA = (TCU_TILE_M * TCU_TILE_K) / TCU_NT;
localparam TCU_NRB = (TCU_TILE_N * TCU_TILE_K) / TCU_NT;
localparam TCU_NRC = (TCU_TILE_M * TCU_TILE_N) / TCU_NT;
localparam TCU_RC = 0;
localparam TCU_WG_RC = TCU_RC;
localparam TCU_WG_RA = 24;
localparam TCU_RA = 10;
localparam TCU_RB = (TCU_NRB == 4) ? 28 : 24;
localparam TCU_UOPS = TCU_M_STEPS * TCU_N_STEPS * TCU_K_STEPS;
localparam TCU_MAX_INPUTS = TCU_TC_K * TCU_MAX_ELT_RATIO;
localparam TCU_MX_MAX_SF = 8;
localparam TCU_EXP_BITS = 10;
localparam TCU_EXP_BITS = 10;
localparam TCU_EXP_BITS = 9;

typedef struct packed { logic is_zero; logic is_sub; logic is_inf; logic is_nan; } fedp_class_t;
typedef struct packed { logic is_inf; logic is_nan; logic sign; } fedp_excep_t;

// Format utility functions (from VX_gpu_pkg)
function logic tcu_fmt_is_int(input logic [4:0] fmt);
    tcu_fmt_is_int = fmt[4];
endfunction

function logic tcu_fmt_is_signed_int(input logic [3:0] int_fmt);
    tcu_fmt_is_signed_int = int_fmt[0];
endfunction

function logic tcu_fmt_is_bfloat(input logic [3:0] float_fmt);
    tcu_fmt_is_bfloat = float_fmt[0];
endfunction

function logic tcu_fmt_is_mx(input logic [4:0] fmt);
    case (fmt)
        5'd10, 5'd11, 5'd8, 5'd9: tcu_fmt_is_mx = 1'b1;
        default: tcu_fmt_is_mx = 1'b0;
    endcase
endfunction

function int unsigned tcu_fmt_width(input logic [4:0] fmt);
    case (fmt)
        5'd2, 5'd3: tcu_fmt_width = 16;
        5'd10, 5'd11, 5'd19, 5'd20: tcu_fmt_width = 4;
        5'd4, 5'd5, 5'd17, 5'd18, 5'd8, 5'd9: tcu_fmt_width = 8;
        5'd0, 5'd16, 5'd1: tcu_fmt_width = 32;
        default: tcu_fmt_width = 0;
    endcase
endfunction

function int unsigned tcu_int_fmt_width(input logic [3:0] fmt);
    case (fmt)
        4'd0: tcu_int_fmt_width = 8;
        4'd1: tcu_int_fmt_width = 16;
        4'd2: tcu_int_fmt_width = 32;
        default: tcu_int_fmt_width = 8;
    endcase
endfunction

    function int unsigned mx_fedp_sf_count(
        input int unsigned data_bits,
        input int unsigned block_elems
    );
        automatic int unsigned sparse_ratio = `VX_CFG_TCU_SPARSE_ENABLED ? 2 : 1;
        automatic int unsigned fedp_elems = TCU_WG_FEDP_K * (32 / data_bits) * sparse_ratio;
        return (fedp_elems + block_elems - 1) / block_elems;
    endfunction
    function int unsigned mx_max_fedp_sf();
        automatic int unsigned max_sf = 1;
    `ifdef VX_CFG_TCU_FP8_ENABLE
        max_sf = `MAX(max_sf, mx_fedp_sf_count(8, 32));
    `endif
    `ifdef VX_CFG_TCU_MXFP4_ENABLE
        max_sf = `MAX(max_sf, mx_fedp_sf_count(4, 32));
    `endif
    `ifdef VX_CFG_TCU_NVFP4_ENABLE
        max_sf = `MAX(max_sf, mx_fedp_sf_count(4, 16));
    `endif
        return max_sf;
    endfunction
    function int exp_bits(input int fmt);
        case (fmt)
            TCU_FP32_ID: return 8;
            TCU_FP16_ID: return 5;
            TCU_BF16_ID: return 8;
            TCU_FP8_ID:  return 4;
            TCU_BF8_ID:  return 5;
            TCU_TF32_ID: return 8;
            default:     return 0;
        endcase
    endfunction
    function int sig_bits(input int fmt);
        case (fmt)
            TCU_FP32_ID: return 23;
            TCU_FP16_ID: return 10;
            TCU_BF16_ID: return 7;
            TCU_FP8_ID:  return 3;
            TCU_BF8_ID:  return 2;
            TCU_TF32_ID: return 10;
            default:     return 0;
        endcase
    endfunction
    function int sign_pos(input int fmt);
        case (fmt)
            TCU_FP32_ID: return 31;
            TCU_FP16_ID: return 15;
            TCU_BF16_ID: return 15;
            TCU_FP8_ID:  return 7;
            TCU_BF8_ID:  return 7;
            TCU_TF32_ID: return 18;
            default:     return 0;
        endcase
    endfunction
    function int unsigned tcu_fmt_width(input logic [TCU_FMT_WIDTH-1:0] fmt);
        case (fmt)
            TCU_FP16_ID, TCU_BF16_ID:
                return 16;
            TCU_MXFP4_ID, TCU_NVFP4_ID, TCU_I4_ID, TCU_U4_ID:
                return 4;
            TCU_FP8_ID,
            TCU_BF8_ID,
            TCU_I8_ID,
            TCU_U8_ID,
            TCU_MXFP8_ID,
            TCU_MXBF8_ID:
                return 8;
            TCU_FP32_ID,
            TCU_I32_ID,
            TCU_TF32_ID:
                return 32;
            default:
                return 0;
        endcase
    endfunction
    function logic tcu_fmt_is_int(input logic [TCU_FMT_WIDTH-1:0] fmt);
        return fmt[TCU_FMT_WIDTH-1];
    endfunction
    function logic tcu_fmt_is_signed_int(input logic [TCU_FMT_WIDTH-2:0] int_fmt);
        return int_fmt[0];
    endfunction
    function logic tcu_fmt_is_bfloat(input logic [TCU_FMT_WIDTH-2:0] float_fmt);
        return float_fmt[0];
    endfunction
    function logic tcu_fmt_is_mx(input logic [TCU_FMT_WIDTH-1:0] fmt);
        case (fmt)
            TCU_MXFP8_ID, TCU_MXBF8_ID, TCU_MXFP4_ID, TCU_NVFP4_ID:
                return 1'b1;
            default:
                return 1'b0;
        endcase
    endfunction
    function int unsigned mx_scale_block_size(input logic [TCU_FMT_WIDTH-1:0] fmt);
        case (fmt)
            TCU_MXFP8_ID, TCU_MXBF8_ID, TCU_MXFP4_ID: return 32;
            TCU_NVFP4_ID:                                          return 16;
            default:                                               return 1;
        endcase
    endfunction
    function int unsigned mx_scale_blocks_k_words(
        input logic [TCU_FMT_WIDTH-1:0] fmt,
        input int unsigned tile_k_words
    );
        automatic int unsigned data_bits = tcu_fmt_width(fmt);
        automatic int unsigned block_elems = mx_scale_block_size(fmt);
        automatic int unsigned tile_elems = (data_bits != 0) ? tile_k_words * (32 / data_bits) : 0;
        return (tile_elems + block_elems - 1) / block_elems;
    endfunction
    function int unsigned mx_scale_blocks_k(input logic [TCU_FMT_WIDTH-1:0] fmt);
        return mx_scale_blocks_k_words(fmt, TCU_TILE_K);
    endfunction
    function logic [4:0] meta_num_cols(input logic [TCU_FMT_WIDTH-1:0] fmt);
        automatic int hw = tcu_fmt_width(fmt) / 2;
        return 5'((TCU_BLOCK_CAP + hw - 1) / hw);
    endfunction
    function int unsigned tcu_meta_stride_words(input logic [TCU_FMT_WIDTH-1:0] fmt);
        automatic int unsigned fb   = tcu_fmt_width(fmt);
        automatic int unsigned elr  = (fb != 0) ? (32 / fb) : 1; // input ratio
        automatic int unsigned rowb = TCU_TC_K * 2 * elr;
        return (TCU_TC_M * rowb + 31) / 32;
    endfunction

localparam NW_WIDTH = `UP(NW_BITS);
localparam NCTA_WIDTH = `UP(NCTA_BITS);
localparam BYTESEL_BITS = (XLENB_W + XLENB_W);
localparam NUM_REGS_BITS = `CLOG2(NUM_REGS);
localparam NUM_XREGS = 2;
localparam SIMD_IDX_W = `UP(SIMD_IDX_BITS);
localparam UUID_WIDTH = 44;
localparam UUID_WIDTH = 44;
localparam UUID_WIDTH = 1;
localparam PC_BITS = `VX_CFG_XLEN;
localparam PC_BITS = (`VX_CFG_XLEN-1);
localparam PC_BITS = (`VX_CFG_XLEN-2);
localparam MEM_ATTR_WIDTH = $bits(mem_bus_attr_t);
localparam INST_OP_BITS = 4;
localparam ISSUE_WIS_W = `UP(ISSUE_WIS_BITS);
localparam INST_ARGS_BITS = 3 + ALU_TYPE_BITS + 20 + 2;
localparam LMEM_DMA_DATA_SIZE = `VX_CFG_LMEM_NUM_BANKS * LSU_WORD_SIZE;

localparam TCU_MAX_INPUTS = 16;

// ─── Behavioral blackboxes for external dependencies ─────────────────────

// VX_pipe_register — pipeline register
module VX_pipe_register #(
    parameter DATAW  = 1,
    parameter RESETW = 0,
    parameter DEPTH  = 1,
    parameter INIT_VALUE = 0
) (
    input  wire              clk,
    input  wire              reset,
    input  wire              enable,
    input  wire [DATAW-1:0]  data_in,
    output wire [DATAW-1:0]  data_out
);
    reg [DATAW-1:0] r [0:DEPTH];
    integer i;
    always_ff @(posedge clk) begin
        if (reset) begin
            for (i = 0; i <= DEPTH; i = i + 1)
                r[i] <= DATAW'(INIT_VALUE);
        end else if (enable) begin
            r[0] <= data_in;
            for (i = 1; i <= DEPTH; i = i + 1)
                r[i] <= r[i-1];
        end
    end
    assign data_out = r[DEPTH];
endmodule

// VX_tcu_tfr_wmul stub removed — use source file version

// VX_ks_adder — carry-select adder (behavioral)
module VX_ks_adder #(
    parameter N = 16, parameter BYPASS = 0
) (
    input  wire [N-1:0] dataa,
    input  wire [N-1:0] datab,
    input  wire         cin,
    output wire [N-1:0] sum,
    output wire         cout
);
    assign {cout, sum} = dataa + datab + N'(cin);
endmodule

// VX_csa_tree — carry-save adder tree (behavioral)
module VX_csa_tree #(
    parameter N = 16, parameter W = 8, parameter K = 6,
    parameter BAL = 1, parameter S = 12
) (
    input  wire [N*W-1:0] operands,
    output wire [S-1:0]   sum,
    output wire [S-1:0]   carry
);
    integer i;
    reg [S-1:0] total;
    always_comb begin
        total = 0;
        for (i = 0; i < N; i = i + 1)
            total = total + S'(operands[i*W +: W]);
    end
    assign sum = total;
    assign carry = 0;
endmodule

// VX_lzc — leading zero count (behavioral)
module VX_lzc #(
    parameter N = 2, parameter REVERSE = 0, parameter LOGN = 1
) (
    input  wire [N-1:0]    data_in,
    output wire [LOGN-1:0] data_out,
    output wire            valid_out
);
    integer i;
    reg [LOGN-1:0] count;
    reg found;
    always_comb begin
        found = 0;
        count = 0;
        for (i = 0; i < N; i = i + 1) begin
            if (!found && data_in[REVERSE ? (N-1-i) : i]) begin
                count = LOGN'(i);
                found = 1;
            end
        end
    end
    assign data_out = count;
    assign valid_out = |data_in;
endmodule

// VX_popcount — population count (behavioral)
module VX_popcount #(
    parameter N = 64, parameter M = 7
) (
    input  wire [N-1:0] data_in,
    output wire [M-1:0] data_out
);
    integer i;
    reg [M-1:0] count;
    always_comb begin
        count = 0;
        for (i = 0; i < N; i = i + 1)
            count = count + M'(data_in[i]);
    end
    assign data_out = count;
endmodule

// VX_generic_arbiter — generic arbiter (behavioral: priority)
module VX_generic_arbiter #(
    parameter NUM_REQS = 4,
    parameter WORD_WIDTH = 1,
    parameter LOG_NUM_REQS = 2
) (
    input  wire [NUM_REQS-1:0]          requests,
    input  wire                          any_in,
    output wire [LOG_NUM_REQS-1:0]      grant_index,
    output wire [NUM_REQS-1:0]          grant_onehot,
    output wire                          grant_valid
);
    integer i;
    reg [LOG_NUM_REQS-1:0] idx;
    reg found;
    always_comb begin
        found = 0;
        idx = 0;
        for (i = 0; i < NUM_REQS; i = i + 1) begin
            if (!found && requests[i]) begin
                idx = LOG_NUM_REQS'(i);
                found = 1;
            end
        end
    end
    assign grant_index = idx;
    assign grant_onehot = found ? (NUM_REQS'(1) << idx) : '0;
    assign grant_valid = found;
endmodule

// VX_fifo_queue — FIFO queue (behavioral: shift register)
module VX_fifo_queue #(
    parameter DATAW = 1,
    parameter DEPTH = 1,
    parameter ALM_FULL = 0,
    parameter ALM_EMPTY = 0
) (
    input  wire              clk,
    input  wire              reset,
    input  wire              push,
    input  wire              pop,
    input  wire [DATAW-1:0]  data_in,
    output wire [DATAW-1:0]  data_out,
    output wire              full,
    output wire              empty
);
    reg [DATAW-1:0] mem [0:DEPTH-1];
    reg [$clog2(DEPTH):0] rptr, wptr, count;
    integer i;

    always_ff @(posedge clk) begin
        if (reset) begin
            rptr <= 0; wptr <= 0; count <= 0;
        end else begin
            if (push && !full) begin
                mem[wptr] <= data_in;
                wptr <= (wptr == DEPTH-1) ? 0 : wptr + 1;
                count <= count + 1;
            end
            if (pop && !empty) begin
                rptr <= (rptr == DEPTH-1) ? 0 : rptr + 1;
                count <= count - 1;
            end
        end
    end
    assign data_out = mem[rptr];
    assign full = (count == DEPTH);
    assign empty = (count == 0);
endmodule

// VX_tcu_tfr_pipe_register — TFR-specific pipeline register (alias)
module VX_tcu_tfr_pipe_register #(
    parameter DATAW  = 1,
    parameter RESETW = 0,
    parameter DEPTH  = 1,
    parameter INIT_VALUE = 0
) (
    input  wire              clk,
    input  wire              reset,
    input  wire              enable,
    input  wire [DATAW-1:0]  data_in,
    output wire [DATAW-1:0]  data_out
);
    VX_pipe_register #(.DATAW(DATAW), .RESETW(RESETW), .DEPTH(DEPTH), .INIT_VALUE(INIT_VALUE))
    u_pipe (.clk(clk), .reset(reset), .enable(enable), .data_in(data_in), .data_out(data_out));
endmodule

"""

# ─── Phase A transforms ──────────────────────────────────────────────────

def strip_preprocessor_blocks(content):
    """Strip preprocessor directives but KEEP their bodies.
    ifdef=keep, ifndef=skip, elsif/else=flip, define/undef/include=remove.
    """
    lines = content.split("\n")
    result = []
    stack = []  # 'keep' or 'skip'

    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Track preprocessor state but REMOVE all directive lines from output
        if stripped.startswith("`ifdef "):
            stack.append('keep')
            i += 1
            continue
        elif stripped.startswith("`ifndef "):
            stack.append('skip')
            i += 1
            continue
        elif stripped.startswith("`elsif ") or stripped.startswith("`else"):
            if stack:
                stack[-1] = 'skip' if stack[-1] == 'keep' else 'keep'
            i += 1
            continue
        elif stripped.startswith("`endif"):
            if stack:
                stack.pop()
            i += 1
            continue
        elif stripped.startswith("`define ") or stripped.startswith("`undef ") or stripped.startswith("`include "):
            i += 1
            continue
        elif stack and stack[-1] == 'skip':
            i += 1
            continue

        result.append(line)
        i += 1

    return "\n".join(result)


def strip_simulation_macros(content):
    """Strip $display, $write, $monitor, TRACE, DBG_TRACE_TCU (multi-line aware)."""
    # Strip $display/$write/$monitor with parenthesis-depth counting
    for pat in ["$display", "$write", "$monitor"]:
        result = []
        i = 0
        while i < len(content):
            idx = content.find(pat, i)
            if idx < 0:
                result.append(content[i:])
                break
            result.append(content[i:idx])
            j = idx + len(pat)
            while j < len(content) and content[j] in (' ', '\t'):
                j += 1
            if j < len(content) and content[j] == '(':
                depth = 1
                j += 1
                while j < len(content) and depth > 0:
                    if content[j] == '(':
                        depth += 1
                    elif content[j] == ')':
                        depth -= 1
                    j += 1
            while j < len(content) and content[j] in (' ', '\t'):
                j += 1
            if j < len(content) and content[j] == ';':
                j += 1
            i = j
        content = "".join(result)

    # Strip TRACE / TRACE_ARRAY (balanced-paren)
    for pat in ["`TRACE_ARRAY1D", "`TRACE_ARRAY", "`TRACE"]:
        result = []
        i = 0
        while i < len(content):
            idx = content.find(pat, i)
            if idx < 0:
                result.append(content[i:])
                break
            result.append(content[i:idx])
            j = idx + len(pat)
            while j < len(content) and content[j] in (' ', '\t'):
                j += 1
            if j < len(content) and content[j] == '(':
                depth = 1
                j += 1
                while j < len(content) and depth > 0:
                    if content[j] == '(':
                        depth += 1
                    elif content[j] == ')':
                        depth -= 1
                    j += 1
            while j < len(content) and content[j] in (' ', '\t', ';'):
                j += 1
            i = j
        content = "".join(result)

    # Strip DBG_TRACE_TCU blocks
    content = re.sub(r'`ifdef\s+DBG_TRACE_TCU.*?`endif[^\n]*\n', '', content, flags=re.DOTALL)

    return content


def strip_simulation_only(content):
    """Strip `ifndef SYNTHESIS ... `endif blocks."""
    lines = content.split('\n')
    result = []
    skip = False
    depth = 0
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("`ifndef SYNTHESIS"):
            skip = True
            depth = 1
            continue
        if skip:
            if stripped.startswith("`ifdef") or stripped.startswith("`ifndef"):
                depth += 1
            elif stripped.startswith("`endif"):
                depth -= 1
                if depth == 0:
                    skip = False
            continue
        result.append(line)
    return '\n'.join(result)


def transform(content):
    """Apply all Phase A transforms."""
    content = strip_preprocessor_blocks(content)
    content = strip_simulation_only(content)
    content = strip_simulation_macros(content)

    # FORCE_BUILTIN_ADDER
    content = re.sub(r'`FORCE_BUILTIN_ADDER\s*\(([^)]+)\)', r'1', content)
    content = re.sub(r'^\s*`FORCE_BUILTIN_ADDER[^\n]*\n?', '', content, flags=re.MULTILINE)

    # Backtick-escaped constants → literals
    for pkg_const in re.findall(r'`(\w+)', content):
        if pkg_const in ('ifdef', 'ifndef', 'endif', 'elsif', 'else', 'define', 'undef', 'include',
                         'TRACE', 'TRACE_ARRAY', 'UNUSED_PARAM', 'UNUSEDWire', 'STATIC_ASSERT',
                         'TRACING_OFF', 'FORCE_BUILTIN_ADDER', 'CLOG2', 'LOG2UP', 'UP', '__MIN',
                         'VX_CFG_XLEN', 'VX_CFG_NUM_THREADS', 'VX_CFG_NUM_WARPS', 'VX_CFG_NUM_TCU_LANES',
                         'VX_CFG_ISSUE_WIDTH', 'VX_CFG_NUM_TCU_BLOCKS',
                         'VX_MEM_LMEM_BASE_ADDR', 'VX_CFG_LMEM_LOG_SIZE', 'VX_CFG_LMEM_NUM_BANKS',
                         'MAP_AOS_SOA',
                         'UNUSED_VAR', 'UNUSED_SPARAM', 'UNUSED_PIN', 'SFORMATF', 'STRING',
                         'SCOPE_IO_DECL', 'SCOPE_IO_BIND', 'SCOPE_IO_UNUSED', 'SCOPE_IO_SWITCH'):
            continue
        if pkg_const in BITS_MAP:
            content = content.replace(f'`{pkg_const}', BITS_MAP[pkg_const])

    # Convert import statements to comments (including inline module imports)
    content = re.sub(r'^\s*import\s+\w+::\*;\s*$', '// [stripped import]', content, flags=re.MULTILINE)
    # Strip inline imports from module declarations: 'module X import Pkg1::*, Pkg2::*; #(' -> 'module X #('
    content = re.sub(r'^(module\s+\w+)\s+import\s+[\w:*,\s]+;\s*', r'\1 ', content, flags=re.MULTILINE)
    # Strip 'parameter reg' → 'parameter' (SystemVerilog type parameter syntax)
    content = re.sub(r'\bparameter\s+reg\b', 'parameter', content)

    # $clog2 → $clog2 (keep — Yosys supports it)
    # $bits() → computed constants
    content = re.sub(r'\$bits\(([^)]+)\)', r'32', content)

    # UNUSED_PARAM / UNUSEDWire / UNUSED_VAR / UNUSED_SPARAM / UNUSED_PIN → empty
    for macro_name in ['UNUSED_PARAM', 'UNUSEDWire', 'STATIC_ASSERT',
                       'UNUSED_VAR', 'UNUSED_SPARAM', 'UNUSED_PIN']:
        result = []
        i = 0
        while i < len(content):
            pat = f"`{macro_name}"
            idx = content.find(pat, i)
            if idx < 0:
                result.append(content[i:])
                break
            result.append(content[i:idx])
            # Skip whitespace after macro name
            j = idx + len(pat)
            while j < len(content) and content[j] in (' ', '\t'):
                j += 1
            if j < len(content) and content[j] == '(':
                depth = 1
                j += 1
                while j < len(content) and depth > 0:
                    if content[j] == '(':
                        depth += 1
                    elif content[j] == ')':
                        depth -= 1
                    j += 1
            i = j
        content = "".join(result)
    # SFORMATF → empty string
    content = re.sub(r'`SFORMATF\s*\([^)]*\)', '""', content)
    # SCOPE_IO_* → empty
    for macro_name in ['SCOPE_IO_DECL', 'SCOPE_IO_BIND', 'SCOPE_IO_UNUSED', 'SCOPE_IO_SWITCH']:
        result = []
        i = 0
        while i < len(content):
            pat = f"`{macro_name}"
            idx = content.find(pat, i)
            if idx < 0:
                result.append(content[i:])
                break
            result.append(content[i:idx])
            j = idx + len(pat)
            while j < len(content) and content[j] in (' ', '\t'):
                j += 1
            if j < len(content) and content[j] == '(':
                depth = 1
                j += 1
                while j < len(content) and depth > 0:
                    if content[j] == '(':
                        depth += 1
                    elif content[j] == ')':
                        depth -= 1
                    j += 1
            i = j
        content = "".join(result)
    # STRING → reg (used as parameter type)
    content = re.sub(r'`STRING\s+', 'reg ', content)
    content = re.sub(r'`STRING', 'reg', content)
    # RUNTIME_ASSERT / ASSIGN_VX_MEM_BUS_IF → empty (debug/synthesis macros)
    for macro_name in ['RUNTIME_ASSERT', 'ASSIGN_VX_MEM_BUS_IF']:
        result = []
        i = 0
        while i < len(content):
            pat = f"`{macro_name}"
            idx = content.find(pat, i)
            if idx < 0:
                result.append(content[i:])
                break
            result.append(content[i:idx])
            j = idx + len(pat)
            while j < len(content) and content[j] in (' ', '\t'):
                j += 1
            if j < len(content) and content[j] == '(':
                depth = 1
                j += 1
                while j < len(content) and depth > 0:
                    if content[j] == '(':
                        depth += 1
                    elif content[j] == ')':
                        depth -= 1
                    j += 1
            i = j
        content = "".join(result)
    # MAX(a,b) → ((a) > (b) ? (a) : (b))
    content = re.sub(r'`MAX\s*\(([^,]+),\s*([^)]+)\)', r'((\1) > (\2) ? (\1) : (\2))', content)

    # `include "..." → remove
    content = re.sub(r'^\s*`include\s+"[^"]*"\s*$', '', content, flags=re.MULTILINE)

    return content


# ─── Phase B: Gen-scoped variable hoisting ───────────────────────────────

def hoist_gen_scoped(mod_text, max_loop=16):
    """Hoist wire/logic/reg declarations from inside for(genvar) blocks to module scope."""
    lines = mod_text.split('\n')
    to_hoist = []

    gen_stack = []
    begin_depth = 0

    for i, line in enumerate(lines):
        s = line.strip()
        if re.search(r'\bbegin\b', s):
            begin_depth += 1

        gm = re.match(r'for\s*\(\s*genvar\s+(\w+)\s*=', s)
        if gm:
            var = gm.group(1)
            lm = re.search(r'begin\s*:\s*(\w+)', s)
            label = lm.group(1) if lm else f'gen{i}'
            gen_stack.append((var, label, begin_depth - 1))

        if re.match(r'^\s*end\b', s) and not re.match(r'^\s*end(module|case|function|task)', s):
            if gen_stack and begin_depth - 1 == gen_stack[-1][2]:
                gen_stack.pop()
            begin_depth = max(0, begin_depth - 1)
            continue

        if gen_stack:
            var, label, _ = gen_stack[-1]
            dm = re.match(r'^[ \t]*(wire|logic|reg)\s+(.*);\s*$', s)
            if dm:
                dtype = dm.group(1)
                rest = dm.group(2).strip()
                width_prefix = ''
                names_part = rest
                wm = re.match(r'((?:\[[^\]]+\]\s*)+)', rest)
                if wm:
                    width_prefix = wm.group(1).strip()
                    names_part = rest[wm.end():].strip()
                elif rest.startswith('signed'):
                    wm2 = re.match(r'signed\s+((?:\[[^\]]+\]\s*)+)', rest)
                    if wm2:
                        width_prefix = 'signed ' + wm2.group(1).strip()
                        names_part = rest[wm2.end():].strip()

                if '=' in names_part:
                    name_candidates = [names_part.strip()]
                else:
                    name_candidates = [n.strip() for n in names_part.split(',')]

                for name_raw in name_candidates:
                    name_raw = name_raw.strip()
                    name_raw = re.sub(r'\s*\[.*$', '', name_raw)
                    name_raw = re.sub(r'\s*=.*$', '', name_raw)
                    name = name_raw.split()[0] if name_raw.split() else ''
                    if not name or not re.match(r'[a-zA-Z_]', name):
                        continue
                    width = width_prefix
                    if width and re.search(rf'\b{re.escape(var)}\b', width):
                        continue
                    if width and re.search(r'[a-zA-Z_]\w*\s*[-+*/]', width):
                        for lp in re.finditer(r'localparam\s+(?:\[.*?\]\s+)?(\w+)\s*=\s*([^;]+);', mod_text):
                            lp_name, lp_val = lp.group(1), lp.group(2).strip()
                            if lp_val.isdigit():
                                width = re.sub(rf'\b{re.escape(lp_name)}\b', lp_val, width)
                        for wm_eval in re.finditer(r'\[(\d+)\s*([-+])\s*(\d+)\s*:\s*(\d+)\]', width):
                            a, op, b, lo = int(wm_eval.group(1)), wm_eval.group(2), int(wm_eval.group(3)), wm_eval.group(4)
                            result = a - b if op == '-' else a + b
                            width = width[:wm_eval.start()] + f'[{result}:{lo}]' + width[wm_eval.end():]
                        if re.search(r'[a-zA-Z_]', re.sub(r'\[|\]|:', '', width)):
                            continue
                    if name and not name.startswith(var):
                        to_hoist.append((i, name, dtype, width, var, label))

    if not to_hoist:
        return mod_text

    def find_gen_scope(line_idx):
        depth = 0
        for j in range(line_idx, -1, -1):
            s = lines[j].strip()
            if re.match(r'^\s*end\b', s) and not re.match(r'^\s*end(module|case|function|task)', s):
                depth += 1
            if re.search(r'\bbegin\b', s):
                depth -= 1
            if depth < 0 and re.match(r'for\s*\(\s*genvar', s):
                start = j
                depth2 = 0
                for k in range(j, len(lines)):
                    sk = lines[k].strip()
                    if re.search(r'\bbegin\b', sk):
                        depth2 += 1
                    if re.match(r'^\s*end\b', sk) and not re.match(r'^\s*end(module|case|function|task)', sk):
                        depth2 -= 1
                        if depth2 < 0:
                            return (start, k)
                return (start, len(lines) - 1)
        return (0, len(lines) - 1)

    decl_scopes = []
    for line_idx, name, dtype, width, var, label in to_hoist:
        start, end = find_gen_scope(line_idx)
        decl_scopes.append((line_idx, name, dtype, width, var, label, start, end))

    from collections import defaultdict
    lines_by_idx = defaultdict(list)
    for entry in decl_scopes:
        lines_by_idx[entry[0]].append(entry)

    for line_idx in sorted(lines_by_idx.keys(), reverse=True):
        entries = lines_by_idx[line_idx]
        scope_start = entries[0][6]
        scope_end = entries[0][7]
        for _, name, dtype, width, var, label, _, _ in entries:
            hname = f'{label}_{name}'
            for j in range(scope_start, scope_end + 1):
                if j == line_idx:
                    continue
                lines[j] = re.sub(rf'(?<!_)\b{re.escape(name)}\b', f'{hname}[{var}]', lines[j])
        lines[line_idx] = ''

    hoisted = []
    seen = set()
    for _, name, dtype, width, var, label in to_hoist:
        hname = f'{label}_{name}'
        if hname in seen:
            continue
        seen.add(hname)
        if width:
            hoisted.append(f'    wire {width} {hname} [0:{max_loop-1}];')
        else:
            hoisted.append(f'    wire [7:0] {hname} [0:{max_loop-1}];')

    result_lines = []
    inserted = False
    for i, line in enumerate(lines):
        result_lines.append(line)
        if not inserted and line.strip() == ');':
            result_lines.append('')
            result_lines.append('    // Phase B: Hoisted generate-scoped wires')
            result_lines.extend(hoisted)
            result_lines.append('')
            inserted = True

    return '\n'.join(result_lines)


# ─── Main ─────────────────────────────────────────────────────────────────

def main():
    # Read and transform each module
    all_modules = []
    seen_modules = set()

    for mod_file in ALL_MODULES:
        # Determine directory
        if mod_file in TFR_MODULES:
            fpath = os.path.join(TFR_DIR, mod_file)
        else:
            fpath = os.path.join(TCU_DIR, mod_file)

        if not os.path.exists(fpath):
            print(f"  WARNING: {mod_file} not found, skipping")
            continue

        with open(fpath) as f:
            content = f.read()

        # Strip copyright header
        lines = content.split('\n')
        mod_start = 0
        for idx, line in enumerate(lines):
            if re.match(r'\s*module\s+', line):
                mod_start = idx
                break

        # Find module name
        m = re.match(r'\s*module\s+(\w+)', lines[mod_start])
        if not m:
            continue
        mod_name = m.group(1)
        if mod_name in seen_modules:
            continue
        seen_modules.add(mod_name)

        # Apply Phase A transforms
        mod_body = '\n'.join(lines[mod_start:])
        mod_body = transform(mod_body)

        # Apply Phase B hoisting
        mod_body = hoist_gen_scoped(mod_body)

        all_modules.append(mod_body)

    # Compose output
    with open(OUT, 'w') as f:
        f.write(HEADER)
        f.write('\n\n')
        for i, mod in enumerate(all_modules):
            f.write(mod)
            f.write('\n\n')

    total_lines = sum(m.count('\n') for m in all_modules) + HEADER.count('\n')
    print(f"Flattened {len(all_modules)} TCU modules -> {OUT}")
    print(f"  File size: {os.path.getsize(OUT)} bytes")
    print(f"  Total lines: {total_lines}")


if __name__ == '__main__':
    main()
