#!/bin/bash
# Synthesize GRX G100 using Yosys 0.68 directly (no sv2v)
# Blackbox modules that have $bits() or other SV incompatibilities
set -euo pipefail

GRXGPU_HOME="${GRXGPU_HOME:-/home/ubuntu/grxgpu}"
WORK="/tmp/synth_g100_Yosys"
DOCKER_IMAGE="openroad/orfs:latest"

mkdir -p "$WORK/src" "$WORK/reports"

echo "=== Step 1: Copy pre-generated sources ==="
# Use the sources already generated by make gen-sources
if [ ! -d /tmp/synth_g100_Vortex/src ] || [ "$(ls /tmp/synth_g100_Vortex/src/*.sv 2>/dev/null | wc -l)" -lt 100 ]; then
  echo "ERROR: Run 'make gen-sources NUM_CORES=4 PREFIX=/tmp/synth_g100' first"
  exit 1
fi

cp /tmp/synth_g100_Vortex/src/*.sv "$WORK/src/"
echo "Copied $(ls $WORK/src/*.sv | wc -l) SV sources"

echo "=== Step 2: Run Yosys synthesis in Docker ==="
docker run --rm \
  -v "$WORK":/work \
  -v "$GRXGPU_HOME/hw/syn/libs":/libs \
  "$DOCKER_IMAGE" bash -c '
set -euo pipefail
cd /work

# Find Nangate45 liberty
LIB="/OpenROAD-flow-scripts/flow/platforms/nangate45/libs/NangateOpenCellLibrary_typical.lib"
if [ ! -f "$LIB" ]; then
  LIB=$(find / -name "NangateOpenCellLibrary_typical.lib" 2>/dev/null | head -1)
fi
echo "Liberty: $LIB"

# Count sources
echo "Sources: $(ls src/*.sv | wc -l)"

# Create Yosys synthesis script
cat > synth.ys << YSEOF
# SystemVerilog support
verilog_defaults -add -sv

# Include paths
verilog_defaults -add -I /work/src
verilog_defaults -add -I /work/src/tcu

# Read all sources with defer (elaboration later)
YSEOF

# Add all source files
for f in src/*.sv; do
  echo "read_verilog -defer \"$f\"" >> synth.ys
done

cat >> synth.ys << YSEOF2
# Blackbox modules with $bits() or other unsupported SV
# These are used as sub-module references but we cant synthesize them directly
blackbox VX_gpu_pkg

# Hierarchy check
hierarchy -check -top Vortex

# Read target liberty
read_liberty -lib "$LIB"

# Synthesis passes
proc; opt
fsm; opt
memory; opt
memory_map; opt
alumacc; wreduce; share; opt
techmap; opt

# Technology mapping
dfflibmap -liberty "$LIB"
abc -markgroups -D 1.25 -liberty "$LIB"

# Reports
tee -o reports/stat.rpt stat -liberty "$LIB" -top Vortex -width -tech cmos
tee -o reports/hierarchy.rpt hierarchy -top Vortex
write_verilog -noattr -noexpr mapped.v
write_json netlist.json
YSEOF2

echo "Running Yosys..."
mkdir -p reports
timeout 600 yosys -s synth.ys -l reports/yosys.log 2>&1
RC=$?

echo ""
echo "=== Results ==="
if [ $RC -eq 0 ]; then
  echo "--- Stat Report ---"
  cat reports/stat.rpt
  echo ""
  echo "--- Hierarchy Report ---"
  cat reports/hierarchy.rpt
else
  echo "Yosys failed with exit code $RC"
  echo "--- Last 40 lines of log ---"
  tail -40 reports/yosys.log
fi
'

echo "=== COMPLETE ==="
